fix: branch 자동 생성 중 issue title 상태 못가져오는거 수정2

diff --git a/.github/workflows/create-iussue.yml b/.github/workflows/create-iussue.yml
--- a/.github/workflows/create-iussue.yml
+++ b/.github/workflows/create-iussue.yml
@@ -20,13 +20,17 @@ jobs:
             - name: Determine Issue Type
               id: determine-type
               run: |
-                  if [[ "${{ github.event.issue.title }}" =~ ^\[(Feature|Style|Setting|Test)\] ]]; then
-                      echo "type=Task" >> $GITHUB_ENV
-                  elif [[ "${{ github.event.issue.title }}" =~ ^\[Bugfix\] ]]; then
+                  if [[ "${{ github.event.issue.title }}" =~ ^\[(Feature|Style|Setting|Test|Bugfix)\] ]]; then
+                    prefix=$(echo "${{ github.event.issue.title }}" | grep -o '^\[[^]]*\]' | tr -d '[]')
+                    echo "prefix=$prefix" >> $GITHUB_ENV
+                    if [[ "$prefix" == "Bugfix" ]]; then
                       echo "type=Bug" >> $GITHUB_ENV
+                    else
+                      echo "type=Task" >> $GITHUB_ENV
+                    fi
                   else
-                      echo "Error: Issue title must start with [Feature], [Style], [Setting], [Test], or [Bugfix]." >&2
-                      exit 1
+                        echo "Error: Issue title must start with [Feature], [Style], [Setting], [Test], or [Bugfix]." >&2
+                        exit 1
                   fi
               shell: bash
 
