fix: branch 자동 생성 중 issue title 상태 못가져오는거 수정

diff --git a/.github/workflows/create-iussue.yml b/.github/workflows/create-iussue.yml
--- a/.github/workflows/create-iussue.yml
+++ b/.github/workflows/create-iussue.yml
@@ -82,8 +82,15 @@ jobs:
 
             - name: Create branch with Ticket number
               run: |
-                  git checkout -b ${{ env.prefix }}/${{ steps.issue-parser.outputs.issueparser_branchName }}/${{ steps.create.outputs.issue }}
-                  git push origin ${{ env.prefix }}/${{ steps.issue-parser.outputs.issueparser_branchName }}/${{ steps.create.outputs.issue }}
+                  prefix="${{ env.prefix }}"
+                  branch_name="${prefix}/${{ steps.issue-parser.outputs.issueparser_branchName }}/${{ steps.create.outputs.issue }}"
+
+                  if ! [[ "$branch_name" =~ ^[a-zA-Z0-9/_-]+$ ]]; then
+                    echo "Error: Invalid branch name $branch_name"
+                    exit 1
+                  fi
+                  git checkout -b "$branch_name"
+                  git push origin "$branch_name"
 
             - name: Update issue title
               uses: actions-cool/issues-helper@v3
